using System;
using System.Text.Json.Serialization;
using OpenHFT.Core.Instruments;
using OpenHFT.Core.Models;

namespace OpenHFT.Core.Books;

public readonly struct BookElement : IEquatable<BookElement>
{
    public readonly string BookName { get; }
    public readonly int InstrumentId { get; }
    public readonly long LastUpdateTime { get; }

    // --- Session-Specific Metrics (e.g., Daily) ---

    /// <summary>
    /// The average entry price for the position opened within the current session.
    /// </summary>
    public readonly Price AvgPrice { get; }

    /// <summary>
    /// The net size of the position resulting from trades within the current session.
    /// </summary>
    public readonly Quantity Size { get; }

    /// <summary>
    /// Realized PnL generated by trading activities within the current session.
    /// </summary>
    public readonly CurrencyAmount RealizedPnL { get; }

    /// <summary>
    /// Total trading volume generated within the current session.
    /// </summary>
    public readonly CurrencyAmount Volume { get; }


    // --- Cumulative Metrics (Total) ---

    /// <summary>
    /// The average entry price of the total cumulative position.
    /// </summary>
    public readonly Price AvgPriceAccum { get; }

    /// <summary>
    /// The total cumulative net size of the position. This represents the actual balance.
    /// </summary>
    public readonly Quantity SizeAccum { get; }

    /// <summary>
    /// The total cumulative realized PnL over the lifetime of this book element.
    /// </summary>
    public readonly CurrencyAmount RealizedPnLAccum { get; }

    /// <summary>
    /// The total cumulative trading volume over the lifetime of this book element.
    /// </summary>
    public readonly CurrencyAmount VolumeAccum { get; }

    /// <summary>
    /// The main constructor to initialize all fields.
    /// </summary>
    [JsonConstructor]
    public BookElement(
        string bookName, int instrumentId, long lastUpdateTime,
        Price avgPrice, Quantity size, CurrencyAmount realizedPnL, CurrencyAmount volume,
        Price avgPriceAccum, Quantity sizeAccum, CurrencyAmount realizedPnLAccum, CurrencyAmount volumeAccum)
    {
        BookName = bookName;
        InstrumentId = instrumentId;
        LastUpdateTime = lastUpdateTime;

        // Session fields
        AvgPrice = avgPrice;
        Size = size;
        RealizedPnL = realizedPnL;
        Volume = volume;

        // Cumulative fields
        AvgPriceAccum = avgPriceAccum;
        SizeAccum = sizeAccum;
        RealizedPnLAccum = realizedPnLAccum;
        VolumeAccum = volumeAccum;
    }

    /// <summary>
    /// Factory method to create a zero-state (empty) BookElement.
    /// Both session and cumulative values are initialized to zero.
    /// </summary>
    public static BookElement CreateEmpty(string bookName, int instrumentId)
    {
        return new BookElement(
            bookName, instrumentId, 0,
            Price.Zero, Quantity.Zero, CurrencyAmount.Zero(Currency.USDT), CurrencyAmount.Zero(Currency.USDT),
            Price.Zero, Quantity.Zero, CurrencyAmount.Zero(Currency.USDT), CurrencyAmount.Zero(Currency.USDT)
        );
    }

    /// <summary>
    /// Factory method to create a BookElement with a pre-existing cumulative (base) position.
    /// The session-specific values are initialized to zero.
    /// </summary>
    public static BookElement CreateWithBasePosition(string bookName, int instrumentId, Quantity baseSize, Price baseAvgPrice)
    {
        return new BookElement(
            bookName, instrumentId, 0,
            Price.Zero, Quantity.Zero, CurrencyAmount.Zero(Currency.USDT), CurrencyAmount.Zero(Currency.USDT), // Session starts at zero
            baseAvgPrice, baseSize, CurrencyAmount.Zero(Currency.USDT), CurrencyAmount.Zero(Currency.USDT) // Cumulative starts with the base position
        );
    }

    public override bool Equals(object? obj) => obj is BookElement other && Equals(other);

    public bool Equals(BookElement other)
    {
        // BookName, InstrumentId, Quantity 등 모든 주요 필드를 비교
        return BookName == other.BookName &&
               InstrumentId == other.InstrumentId &&
               AvgPrice.Equals(other.AvgPrice) &&
               Size.Equals(other.Size) &&
               RealizedPnL.Equals(other.RealizedPnL) &&
               Volume.Equals(other.Volume);
    }

    public override int GetHashCode()
    {
        var hash = new HashCode();
        hash.Add(BookName);
        hash.Add(InstrumentId);
        hash.Add(AvgPrice);
        hash.Add(Size);
        hash.Add(RealizedPnL);
        hash.Add(Volume);
        return hash.ToHashCode();
    }

    public static bool operator ==(BookElement left, BookElement right) => left.Equals(right);
    public static bool operator !=(BookElement left, BookElement right) => !left.Equals(right);
}