global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "openhft-engine"
    static_configs:
      - targets: ["openhft-engine:9091"]
    scrape_interval: 1s
    metrics_path: /metrics
    
  - job_name: "openhft-api"
    static_configs:
      - targets: ["openhft-engine:5000"]
    scrape_interval: 5s
    metrics_path: /metrics
